name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  # call from another workflow
  workflow_call:
    inputs:
      title:
        required: true
        type: string
  # call from user via github wui
  workflow_dispatch:
    inputs:
      branch:
        description: 'Branch name'
        required: true
        default: 'main'
      warning_analyzer:
        required: true
        default: true
        type: boolean
# defaults:
#   run:
#     shell: bash
#     working-directory: workdir
jobs:
  build:
    runs-on: ubuntu-latest
    # defaults: # this overrides defaults at the level of workflow
    #   run:
    #     shell: bash
    #     working-directory: workdir
    outputs: # it is needed to pass outputs between jobs
      build-stage: ${{ steps.build.outputs.BUILD_STAGE }}
    steps:
      - name: checkout
        run: echo Branch name ${{ github.event.inputs.branch }}
      - name: build
        id: build # it is needed to pass variable between steps
        run: |
          echo build is running
          echo "BUILD_STAGE=debug" >> $GITHUB_OUTPUT
      - name: warning-analyzer
        if: ${{ github.event.inputs.warning_analyzer == 'true' || github.event_name != 'workflow_dispatch' }}
        run: |
          echo checking warnings
          echo "The build stage is ${{ steps.build.outputs.BUILD_STAGE}}"
      - name: post-action
        run: echo uploading artifacts
  post-build:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Get stage
        run: echo "The build stage is ${{ needs.build.outputs.build-stage }}"
  ut:
    runs-on: ubuntu-latest
    steps:
      - name: test 1
        run: | 
          ls -la
          touch test.txt
          pwd
          ls -la
      - name: test 2
        run: | 
          ls -la
          touch test2.txt
          pwd
          ls -la
          echo test
        
