name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:
    inputs:
      branch:
        description: 'Branch name'
        required: true
        default: 'main'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run a one-line script
        run: echo Hello, world!
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
      - name: test
        run: echo test
      - name: test 1
        run: echo test 1
      - name: test 2
        run: echo test 2
      - name: test 3
        run: echo test 3
  ut:
    runs-on: ubuntu-latest
    steps:
      - name: test 1
        run: | 
          ls -la
          touch test.txt
          pwd
          ls -la
          sleep 60
      - name: test 2
        run: | 
          ls -la
          touch test2.txt
          pwd
          ls -la
          sleep 60
        
