name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:
    inputs:
      branch:
        description: 'Branch name'
        required: true
        default: 'main'
      warning_analyzer:
        required: true
        default: true
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        run: echo checkout
      - name: build
        run: echo building
      - name: warning-analyzer
        if: ${{ github.event.inputs.warning_analyzer }}
        run: echo checking warnings
      - name: post-action
        run: echo uploading artifacts
  ut:
    runs-on: ubuntu-latest
    steps:
      - name: test 1
        run: | 
          ls -la
          touch test.txt
          pwd
          ls -la
          sleep 60
      - name: test 2
        run: | 
          ls -la
          touch test2.txt
          pwd
          ls -la
        
