name: print-text
on:
  workflow_call:
    inputs:
      text:
        required: true
        type: string
jobs:
  my-job:
    runs-on: ubuntu-latest
    steps:
      - name: pring text
        run: echo ${{ inputs.text }}
